# Pandas
- Pandas is an open-source software library for the Python programming language, primarily used for data manipulation and analysis.
- It provides data structures and operations for manipulating numerical tables and time series, making it a fundamental tool in the data science ecosystem.

In [5]:
import pandas as pd

### Series

In [10]:
A = pd.Series([2,3,4,5], index=['a','b','c','d'])
print(A.values)
print(type(A.values))
print(type(A))
print(A['a'])
print(A['a':'c'])

[2 3 4 5]
<class 'numpy.ndarray'>
<class 'pandas.core.series.Series'>
2
a    2
b    3
c    4
dtype: int64

In [17]:
grads_dict = {'A':4,'B':3.5,'C':3,'D':2.5}
grads = pd.Series(grads_dict)
print(grads.values)

marks_dict = {'A':85,'B':75,'C':65,'D':55}
marks = pd.Series(marks_dict)
print(marks)

print(marks['A'])
print(marks[0:2])

[4.  3.5 3.  2.5]
A    85
B    75
C    65
D    55
dtype: int64
85
A    85
B    75
dtype: int64

### DataFrames
- 2d dimensional data

In [24]:
D = pd.DataFrame({'Marks':marks, 'Grades':grads})
print(D)
print(D.T)

print(D.values[2,0])
print(D.columns)

D['ScaledMarks'] = 100*(D['Marks']/90)  # Add a new column
print(D)
del(D['ScaledMarks'])  # Delete column
print(D)

   Marks  Grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5
           A     B     C     D
Marks   85.0  75.0  65.0  55.0
Grades   4.0   3.5   3.0   2.5
65.0
Index(['Marks', 'Grades'], dtype='object')
   Marks  Grades  ScaledMarks
A     85     4.0    94.444444
B     75     3.5    83.333333
C     65     3.0    72.222222
D     55     2.5    61.111111
   Marks  Grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5

### NaN

In [37]:
A = pd.DataFrame([{'a':1,'b':4},{'b':-3,'c':9}])
print(A)
print(A.fillna(0))

     a  b    c
0  1.0  4  NaN
1  NaN -3  9.0
     a  b    c
0  1.0  4  0.0
1  0.0 -3  9.0

### loc
- To handle explicit and implicit indexing
- In implicit indexing while slicing last index is considered while in explicit not.

In [43]:
A = pd.Series(['a','b','c'], index=[1,3,5])   # Here a,b,c are implicit endex and 1,3,5 are explicit index
print(A[1])        # explicit index
print(A[1:3])      # implicit index
print(A.loc[1:3])  # explicit index -> 1 and 3
print(A.iloc[1:3]) # implicit index

print(D)
print(D.iloc[2,:])
print(D.iloc[::-1,:])

a
3    b
5    c
dtype: object
1    a
3    b
dtype: object
3    b
5    c
dtype: object
   Marks  Grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5
Marks     65.0
Grades     3.0
Name: C, dtype: float64
   Marks  Grades
D     55     2.5
C     65     3.0
B     75     3.5
A     85     4.0

## csv files

In [48]:
from sklearn.impute import SimpleImputer

In [63]:
# Reading Data
df = pd.read_csv('/Users/compact.csv')
print(df.head(10))

       country        date  total_cases  new_cases  new_cases_smoothed  \
0  Afghanistan  2020-01-01          NaN        NaN                 NaN
1  Afghanistan  2020-01-02          NaN        NaN                 NaN
2  Afghanistan  2020-01-03          NaN        NaN                 NaN
3  Afghanistan  2020-01-04          0.0        0.0                 NaN
4  Afghanistan  2020-01-05          0.0        0.0                 NaN
5  Afghanistan  2020-01-06          0.0        0.0                 NaN
6  Afghanistan  2020-01-07          0.0        0.0                 NaN
7  Afghanistan  2020-01-08          0.0        0.0                 NaN
8  Afghanistan  2020-01-09          0.0        0.0                 0.0
9  Afghanistan  2020-01-10          0.0        0.0                 0.0

   total_cases_per_million  new_cases_per_million  \
0                      NaN                    NaN
1                      NaN                    NaN
2                      NaN                    NaN
3                      0.0                    0.0
4                      0.0                    0.0
5                      0.0                    0.0
6                      0.0                    0.0
7                      0.0                    0.0
8                      0.0                    0.0
9                      0.0                    0.0

   new_cases_smoothed_per_million  total_deaths  new_deaths  ...  population  \
0                             NaN           NaN         NaN  ...  40578801.0
1                             NaN           NaN         NaN  ...  40578801.0
2                             NaN           NaN         NaN  ...  40578801.0
3                             NaN           0.0         0.0  ...  40578801.0
4                             NaN           0.0         0.0  ...  40578801.0
5                             NaN           0.0         0.0  ...  40578801.0
6                             NaN           0.0         0.0  ...  40578801.0
7                             NaN           0.0         0.0  ...  40578801.0
8                             0.0           0.0         0.0  ...  40578801.0
9                             0.0           0.0         0.0  ...  40578801.0

   population_density  median_age  life_expectancy  gdp_per_capita  \
0           62.215477   16.752001        65.616997     1516.273315
1           62.215477   16.752001        65.616997     1516.273315
2           62.215477   16.752001        65.616997     1516.273315
3           62.215477   16.752001        65.616997     1516.273315
4           62.215477   16.752001        65.616997     1516.273315
5           62.215477   16.752001        65.616997     1516.273315
6           62.215477   16.752001        65.616997     1516.273315
7           62.215477   16.752001        65.616997     1516.273315
8           62.215477   16.752001        65.616997     1516.273315
9           62.215477   16.752001        65.616997     1516.273315

   extreme_poverty  diabetes_prevalence  handwashing_facilities  \
0              NaN                 10.9               48.214695
1              NaN                 10.9               48.214695
2              NaN                 10.9               48.214695
3              NaN                 10.9               48.214695
4              NaN                 10.9               48.214695
5              NaN                 10.9               48.214695
6              NaN                 10.9               48.214695
7              NaN                 10.9               48.214695
8              NaN                 10.9               48.214695
9              NaN                 10.9               48.214695

   hospital_beds_per_thousand  human_development_index
0                        0.39                      NaN
1                        0.39                      NaN
2                        0.39                      NaN
3                        0.39                      NaN
4                        0.39                      NaN
5                        0.39                      NaN
6                        0.39                      NaN
7                        0.39                      NaN
8                        0.39                      NaN
9                        0.39                      NaN

[10 rows x 61 columns]

In [64]:
# Modifying Data
df.drop(['extreme_poverty','human_development_index'], axis=1, inplace=True) # inplace=true means changes will reflect in df variable itself
df.rename(columns={'date':'observation_date'}, inplace=True)
df['observation_date'] = pd.to_datetime(df['observation_date'])
print(df.head(10))

print(df.describe())
print(df.info())
print(df.fillna('NA'))

       country observation_date  total_cases  new_cases  new_cases_smoothed  \
0  Afghanistan       2020-01-01          NaN        NaN                 NaN
1  Afghanistan       2020-01-02          NaN        NaN                 NaN
2  Afghanistan       2020-01-03          NaN        NaN                 NaN
3  Afghanistan       2020-01-04          0.0        0.0                 NaN
4  Afghanistan       2020-01-05          0.0        0.0                 NaN
5  Afghanistan       2020-01-06          0.0        0.0                 NaN
6  Afghanistan       2020-01-07          0.0        0.0                 NaN
7  Afghanistan       2020-01-08          0.0        0.0                 NaN
8  Afghanistan       2020-01-09          0.0        0.0                 0.0
9  Afghanistan       2020-01-10          0.0        0.0                 0.0

   total_cases_per_million  new_cases_per_million  \
0                      NaN                    NaN
1                      NaN                    NaN
2                      NaN                    NaN
3                      0.0                    0.0
4                      0.0                    0.0
5                      0.0                    0.0
6                      0.0                    0.0
7                      0.0                    0.0
8                      0.0                    0.0
9                      0.0                    0.0

   new_cases_smoothed_per_million  total_deaths  new_deaths  ...  code  \
0                             NaN           NaN         NaN  ...   AFG
1                             NaN           NaN         NaN  ...   AFG
2                             NaN           NaN         NaN  ...   AFG
3                             NaN           0.0         0.0  ...   AFG
4                             NaN           0.0         0.0  ...   AFG
5                             NaN           0.0         0.0  ...   AFG
6                             NaN           0.0         0.0  ...   AFG
7                             NaN           0.0         0.0  ...   AFG
8                             0.0           0.0         0.0  ...   AFG
9                             0.0           0.0         0.0  ...   AFG

   continent  population  population_density  median_age  life_expectancy  \
0       Asia  40578801.0           62.215477   16.752001        65.616997
1       Asia  40578801.0           62.215477   16.752001        65.616997
2       Asia  40578801.0           62.215477   16.752001        65.616997
3       Asia  40578801.0           62.215477   16.752001        65.616997
4       Asia  40578801.0           62.215477   16.752001        65.616997
5       Asia  40578801.0           62.215477   16.752001        65.616997
6       Asia  40578801.0           62.215477   16.752001        65.616997
7       Asia  40578801.0           62.215477   16.752001        65.616997
8       Asia  40578801.0           62.215477   16.752001        65.616997
9       Asia  40578801.0           62.215477   16.752001        65.616997

   gdp_per_capita  diabetes_prevalence  handwashing_facilities  \
0     1516.273315                 10.9               48.214695
1     1516.273315                 10.9               48.214695
2     1516.273315                 10.9               48.214695
3     1516.273315                 10.9               48.214695
4     1516.273315                 10.9               48.214695
5     1516.273315                 10.9               48.214695
6     1516.273315                 10.9               48.214695
7     1516.273315                 10.9               48.214695
8     1516.273315                 10.9               48.214695
9     1516.273315                 10.9               48.214695

   hospital_beds_per_thousand
0                        0.39
1                        0.39
2                        0.39
3                        0.39
4                        0.39
5                        0.39
6                        0.39
7                        0.39
8                        0.39
9                        0.39

[10 rows x 59 columns]
                    observation_date   total_cases     new_cases  \
count                         526981  5.129400e+05  5.097140e+05
mean   2022-10-24 19:35:12.319799552  1.406776e+07  1.066026e+04
min              2020-01-01 00:00:00  0.000000e+00  0.000000e+00
25%              2021-05-29 00:00:00  9.106000e+03  0.000000e+00
50%              2022-10-20 00:00:00  8.285800e+04  0.000000e+00
75%              2024-03-21 00:00:00  1.067030e+06  6.600000e+01
max              2025-12-31 00:00:00  7.784487e+08  8.401906e+06
std                              NaN  7.339679e+07  1.180139e+05

       new_cases_smoothed  total_cases_per_million  new_cases_per_million  \
count        5.085090e+05            512940.000000          509714.000000
mean         1.068554e+04            129531.959020             100.027256
min          0.000000e+00                 0.000000               0.000000
25%          0.000000e+00              2988.496300               0.000000
50%          5.000000e+00             45305.938000               0.000000
75%          2.025714e+02            191251.360000               7.696837
max          6.402033e+06            769887.940000          231770.160000
std          1.007841e+05            174517.109919             988.882692

       new_cases_smoothed_per_million  total_deaths     new_deaths  \
count                   508509.000000  5.129400e+05  510571.000000
mean                       100.268227  1.538902e+05     101.862744
min                          0.000000  0.000000e+00       0.000000
25%                          0.000000  6.700000e+01       0.000000
50%                          0.906908  1.016000e+03       0.000000
75%                         33.073250  1.226600e+04       0.000000
max                      37737.870000  7.099773e+06   57167.000000
std                        508.756930  7.727792e+05     808.813101

       new_deaths_smoothed  ...  new_people_vaccinated_smoothed  \
count        509359.000000  ...                    2.028400e+05
mean            102.106887  ...                    1.001362e+05
min               0.000000  ...                    0.000000e+00
25%               0.000000  ...                    1.942857e+01
50%               0.000000  ...                    5.660340e+02
75%               2.000000  ...                    8.046823e+03
max           14820.714000  ...                    2.107126e+07
std             744.965848  ...                    7.586046e+05

       new_people_vaccinated_smoothed_per_hundred    population  \
count                               202840.000000  5.099530e+05
mean                                     0.069271  1.314337e+08
min                                      0.000000  5.010000e+02
25%                                      0.000768  4.553260e+05
50%                                      0.010297  6.035057e+06
75%                                      0.064207  2.971538e+07
max                                     11.735082  8.021407e+09
std                                      0.172268  6.682698e+08

       population_density     median_age  life_expectancy  gdp_per_capita  \
count       501705.000000  503773.000000    505833.000000   411548.000000
mean           380.677947      31.180669        73.456776    22527.008386
min              0.136360      14.298000        18.817699      708.178284
25%             36.265621      22.243999        68.748703     5155.620117
50%             92.081375      31.683001        74.695999    14740.009766
75%            237.440125      39.080002        78.788101    34663.496094
max          21342.697266      59.875000        85.746399   117746.992188
std           1732.683804       9.666076         7.655482    22553.165403

       diabetes_prevalence  handwashing_facilities  hospital_beds_per_thousand
count        444571.000000           238618.000000               318747.000000
mean              9.057508               59.257909                    3.183356
min               1.100000                3.440189                    0.300000
25%               5.600000               26.200474                    1.320000
50%               7.400000               70.153603                    2.600000
75%              11.100000               88.469353                    4.260000
max              30.799999              100.000000                   13.800000
std               5.234436               31.877516                    2.566271

[8 rows x 56 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 526981 entries, 0 to 526980
Data columns (total 59 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   country                                     526981 non-null  object
 1   observation_date                            526981 non-null  datetime64[ns]
 2   total_cases                                 512940 non-null  float64
 3   new_cases                                   509714 non-null  float64
 4   new_cases_smoothed                          508509 non-null  float64
 5   total_cases_per_million                     512940 non-null  float64
 6   new_cases_per_million                       509714 non-null  float64
 7   new_cases_smoothed_per_million              508509 non-null  float64
 8   total_deaths                                512940 non-null  float64
 9   new_deaths                                  510571 non-null  float64
 10  new_deaths_smoothed                         509359 non-null  float64
 11  total_deaths_per_million                    512940 non-null  float64
 12  new_deaths_per_million                      510571 non-null  float64
 13  new_deaths_smoothed_per_million             509359 non-null  float64
 14  excess_mortality                            13672 non-null   float64
 15  excess_mortality_cumulative                 13672 non-null   float64
 16  excess_mortality_cumulative_absolute        13672 non-null   float64
 17  excess_mortality_cumulative_per_million     13638 non-null   float64
 18  hosp_patients                               40656 non-null   float64
 19  hosp_patients_per_million                   40656 non-null   float64
 20  weekly_hosp_admissions                      24497 non-null   float64
 21  weekly_hosp_admissions_per_million          24497 non-null   float64
 22  icu_patients                                39116 non-null   float64
 23  icu_patients_per_million                    39116 non-null   float64
 24  weekly_icu_admissions                       10993 non-null   float64
 25  weekly_icu_admissions_per_million           10993 non-null   float64
 26  stringency_index                            202760 non-null  float64
 27  reproduction_rate                           185683 non-null  float64
 28  total_tests                                 79387 non-null   float64
 29  new_tests                                   75403 non-null   float64
 30  total_tests_per_thousand                    79387 non-null   float64
 31  new_tests_per_thousand                      75403 non-null   float64
 32  new_tests_smoothed                          103965 non-null  float64
 33  new_tests_smoothed_per_thousand             103965 non-null  float64
 34  positive_rate                               101560 non-null  float64
 35  tests_per_case                              100645 non-null  float64
 36  total_vaccinations                          83222 non-null   float64
 37  people_vaccinated                           79011 non-null   float64
 38  people_fully_vaccinated                     77011 non-null   float64
 39  total_boosters                              58784 non-null   float64
 40  new_vaccinations                            68876 non-null   float64
 41  new_vaccinations_smoothed                   202840 non-null  float64
 42  total_vaccinations_per_hundred              83222 non-null   float64
 43  people_vaccinated_per_hundred               79011 non-null   float64
 44  people_fully_vaccinated_per_hundred         77011 non-null   float64
 45  total_boosters_per_hundred                  58784 non-null   float64
 46  new_vaccinations_smoothed_per_million       202840 non-null  float64
 47  new_people_vaccinated_smoothed              202840 non-null  float64
 48  new_people_vaccinated_smoothed_per_hundred  202840 non-null  float64
 49  code                                        503845 non-null  object
 50  continent                                   487365 non-null  object
 51  population                                  509953 non-null  float64
 52  population_density                          501705 non-null  float64
 53  median_age                                  503773 non-null  float64
 54  life_expectancy                             505833 non-null  float64
 55  gdp_per_capita                              411548 non-null  float64
 56  diabetes_prevalence                         444571 non-null  float64
 57  handwashing_facilities                      238618 non-null  float64
 58  hospital_beds_per_thousand                  318747 non-null  float64
dtypes: datetime64[ns](1), float64(55), object(3)
memory usage: 237.2+ MB
None
            country observation_date total_cases new_cases new_cases_smoothed  \
0       Afghanistan       2020-01-01          NA        NA                 NA
1       Afghanistan       2020-01-02          NA        NA                 NA
2       Afghanistan       2020-01-03          NA        NA                 NA
3       Afghanistan       2020-01-04         0.0       0.0                 NA
4       Afghanistan       2020-01-05         0.0       0.0                 NA
...             ...              ...         ...       ...                ...
526976     Zimbabwe       2025-08-20    266434.0       0.0                0.0
526977     Zimbabwe       2025-08-21    266434.0       0.0                0.0
526978     Zimbabwe       2025-08-22    266434.0       0.0                0.0
526979     Zimbabwe       2025-08-23    266434.0       0.0                0.0
526980     Zimbabwe       2025-08-24    266434.0       0.0                0.0

       total_cases_per_million new_cases_per_million  \
0                           NA                    NA
1                           NA                    NA
2                           NA                    NA
3                          0.0                   0.0
4                          0.0                   0.0
...                        ...                   ...
526976               16580.611                   0.0
526977               16580.611                   0.0
526978               16580.611                   0.0
526979               16580.611                   0.0
526980               16580.611                   0.0

       new_cases_smoothed_per_million total_deaths new_deaths  ... code  \
0                                  NA           NA         NA  ...  AFG
1                                  NA           NA         NA  ...  AFG
2                                  NA           NA         NA  ...  AFG
3                                  NA          0.0        0.0  ...  AFG
4                                  NA          0.0        0.0  ...  AFG
...                               ...          ...        ...  ...  ...
526976                            0.0       5740.0        0.0  ...  ZWE
526977                            0.0       5740.0        0.0  ...  ZWE
526978                            0.0       5740.0        0.0  ...  ZWE
526979                            0.0       5740.0        0.0  ...  ZWE
526980                            0.0       5740.0        0.0  ...  ZWE

       continent  population population_density median_age life_expectancy  \
0           Asia  40578801.0          62.215477  16.752001       65.616997
1           Asia  40578801.0          62.215477  16.752001       65.616997
2           Asia  40578801.0          62.215477  16.752001       65.616997
3           Asia  40578801.0          62.215477  16.752001       65.616997
4           Asia  40578801.0          62.215477  16.752001       65.616997
...          ...         ...                ...        ...             ...
526976    Africa  16069010.0           41.53809  17.683001         62.3601
526977    Africa  16069010.0           41.53809  17.683001         62.3601
526978    Africa  16069010.0           41.53809  17.683001         62.3601
526979    Africa  16069010.0           41.53809  17.683001         62.3601
526980    Africa  16069010.0           41.53809  17.683001         62.3601

       gdp_per_capita diabetes_prevalence handwashing_facilities  \
0         1516.273315                10.9              48.214695
1         1516.273315                10.9              48.214695
2         1516.273315                10.9              48.214695
3         1516.273315                10.9              48.214695
4         1516.273315                10.9              48.214695
...               ...                 ...                    ...
526976    2207.957031                 2.1              42.456093
526977    2207.957031                 2.1              42.456093
526978    2207.957031                 2.1              42.456093
526979    2207.957031                 2.1              42.456093
526980    2207.957031                 2.1              42.456093

       hospital_beds_per_thousand
0                            0.39
1                            0.39
2                            0.39
3                            0.39
4                            0.39
...                           ...
526976                        1.7
526977                        1.7
526978                        1.7
526979                        1.7
526980                        1.7

[526981 rows x 59 columns]

In [81]:
# Fetching Data

df2 = df.groupby('country')[['total_cases', 'new_cases', 'total_deaths']].sum().reset_index()
print(df2)

df2 = df.groupby(['country', 'observation_date'])[['total_cases', 'new_cases', 'total_deaths']].sum().reset_index()
print(df2)

df3 = df2[df2['total_cases']>100]
print(df3)

                                               country   total_cases  \
0                                          Afghanistan  3.373140e+08
1                                               Africa  1.958007e+10
2                                              Albania  4.864377e+08
3                                              Algeria  4.270483e+08
4                                       American Samoa  1.013716e+07
..                                                 ...           ...
257                  World excl. China and South Korea  8.793242e+11
258  World excl. China, South Korea, Japan and Sing...  8.383532e+11
259                                              Yemen  1.860946e+07
260                                             Zambia  5.093094e+08
261                                           Zimbabwe  3.794344e+08

       new_cases  total_deaths
0       235214.0  1.258689e+07
1     13064968.0  4.062112e+08
2       337202.0  5.719974e+06
3       272394.0  1.107911e+07
4         8359.0  4.141300e+04
..           ...           ...
257  644530236.0  1.058480e+10
258  607719957.0  1.049299e+10
259      11945.0  3.454665e+06
260     349892.0  6.288508e+06
261     266435.0  8.607380e+06

[262 rows x 4 columns]
            country observation_date  total_cases  new_cases  total_deaths
0       Afghanistan       2020-01-01          0.0        0.0           0.0
1       Afghanistan       2020-01-02          0.0        0.0           0.0
2       Afghanistan       2020-01-03          0.0        0.0           0.0
3       Afghanistan       2020-01-04          0.0        0.0           0.0
4       Afghanistan       2020-01-05          0.0        0.0           0.0
...             ...              ...          ...        ...           ...
526976     Zimbabwe       2025-08-20     266434.0        0.0        5740.0
526977     Zimbabwe       2025-08-21     266434.0        0.0        5740.0
526978     Zimbabwe       2025-08-22     266434.0        0.0        5740.0
526979     Zimbabwe       2025-08-23     266434.0        0.0        5740.0
526980     Zimbabwe       2025-08-24     266434.0        0.0        5740.0

[526981 rows x 5 columns]
            country observation_date  total_cases  new_cases  total_deaths
89      Afghanistan       2020-03-30        106.0       15.0           3.0
90      Afghanistan       2020-03-31        114.0        8.0           4.0
91      Afghanistan       2020-04-01        166.0       52.0           4.0
92      Afghanistan       2020-04-02        192.0       26.0           4.0
93      Afghanistan       2020-04-03        194.0        2.0           4.0
...             ...              ...          ...        ...           ...
526976     Zimbabwe       2025-08-20     266434.0        0.0        5740.0
526977     Zimbabwe       2025-08-21     266434.0        0.0        5740.0
526978     Zimbabwe       2025-08-22     266434.0        0.0        5740.0
526979     Zimbabwe       2025-08-23     266434.0        0.0        5740.0
526980     Zimbabwe       2025-08-24     266434.0        0.0        5740.0

[460592 rows x 5 columns]